version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: ingestor_db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ingestor
      POSTGRES_PASSWORD: ingestor
      POSTGRES_DB: ingestor_dev
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ingestor -d ingestor_dev"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  pgdata:
