services:
  db:
    image: postgres:16-alpine
    container_name: rent_db
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: rent
      POSTGRES_PASSWORD: rent
      POSTGRES_DB: rent_dev
    volumes:
      - pgdata_rent:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rent -d rent_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: bus_redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata_rent:
  redis_data:
